from tkinter import font

WIDTH = 800
HEIGHT = 600
GIF_WIDTH = 150
GIF_HEIGHT = 75
GIF_PADDINGX = 20
GIF_PADDINGY = 10
TABS_PADDINGX = 20
TABS_PADDINGY = 10
WIDGET_INTERVALX = 15
WIDGET_INTERVALY = 15
SEARCH_BAR_PADDING_Y = 15
SEARCH_RESULT_WIDTH = 600
SEARCH_RESULT_HEIGHT = 400
SEARCH_RESULT_TRAY_WIDTH = 400
SEARCH_RESULT_TRAY_HEIGHT = 30
SEARCH_ENTRY_WIDTH = 300
SEARCH_ENTRY_HEIGHT = 25
SEARCH_BUTTON_WIDTH = 60
SEARCH_BUTTON_HEIGHT = 25
VIEW_BUTTON_WIDTH = 80
VIEW_BUTTON_HEIGHT = 60
VIEW_BUTTON_PADDINGY = 20

cFont = None

def initFonts():
    global cFont
    cFont = font.Font(family="맑은 고딕", size=10, weight="normal", slant="roman")